### ISSUE TITLE
the website motive is not clear give clear title name

### ISSUE THREAD

**Issue by Antoniohayato** [LunarMarathon/graphToTable#9]
we can add login and sign in button for the users.
we can give in large font the button to create table
we can add navigation bar in this
we can add footer also which provide further information about the owner and the website
make website more interesting by adding background images, hovering effect to the buttons, good colour combinations,

**Comment by LunarMarathon** [comment]
Sorry but I don't need any of these at the moment. The functionality of the site needs to be improved first after which these could be considered but since it's a single page I wonder if I'll still need a navbar, footer etc. I'll post a more detailed issue later if needed. Thanks for your interest, you could maybe check the other issues and see if you can contribute to those
